name: capstone-pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch
      
permissions:
      id-token: write
      contents: read
      
jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the repository code

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Log in to Azure using credentials from secrets
  
    - name: Azure CLI script  # Verify Azure account details
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az account show  

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest  # Set up Terraform with the latest version
        
    - name: Install prerequisites # Install tools using tools.sh script
      run: |
        chmod +x prerequisitie-install/tools.sh
        prerequisitie-install/tools.sh  # Execute the tools.sh script
 
    - name: Install NGINX Ingress Controller # Install NGINX Ingress Controller
      run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.1/deploy/static/provider/cloud/deploy.yaml
      
    - name: Deploy Kubernetes resources # Deploy application and related Kubernetes resources
      run: |
        kubectl apply -f k8s-deployments/sockshop.yaml
        kubectl apply -f k8s-deployments/ingress.yaml
        kubectl apply -f k8s-deployments/issuer.yaml  


